import User from "@/User/interface";

const users: User[] = [
    {
        _id: "8c8efc4b-78f5-4824-99db-2ef41c2c4fd9",
        firstName: "Erik",
        lastName: "Babajanyan",
        username: "@Lucifer",
        email: "erik.babajanyan10@gmail.com",
        password: "Abc123456+-",
    },
    {
        _id: "1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed",
        firstName: "Manvel",
        lastName: "Khachatryan",
        username: "@Manvel505",
        email: "exempl@gmail.com",
        password: "password",
    },
    {
        _id: "2b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bec",
        firstName: "John",
        lastName: "Doe",
        username: "@JohnDoe",
        email: "john.doe@example.com",
        password: "securepassword",
    },
    {
        _id: "3b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed",
        firstName: "Jane",
        lastName: "Smith",
        username: "@JaneSmith",
        email: "jane.smith@example.com",
        password: "qwerty123",
    },
    {
        _id: "4b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bee",
        firstName: "Alice",
        lastName: "Johnson",
        username: "@AliceJ",
        email: "alice.johnson@example.com",
        password: "password123",
    },
    {
        _id: "5b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bef",
        firstName: "Bob",
        lastName: "Smith",
        username: "@BobSmith",
        email: "bob.smith@example.com",
        password: "abc123",
    },
    {
        _id: "6b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bea",
        firstName: "Emily",
        lastName: "Jones",
        username: "@EmilyJ",
        email: "emily.jones@example.com",
        password: "password456",
    },
    {
        _id: "7b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4beb",
        firstName: "David",
        lastName: "Brown",
        username: "@DavidB",
        email: "david.brown@example.com",
        password: "securepass",
    },
    {
        _id: "8b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bec",
        firstName: "Emma",
        lastName: "Wilson",
        username: "@EmmaW",
        email: "emma.wilson@example.com",
        password: "password789",
    },
    {
        _id: "9b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed",
        firstName: "Michael",
        lastName: "Taylor",
        username: "@MichaelT",
        email: "michael.taylor@example.com",
        password: "pass1234",
    },
    {
        _id: "0b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bef",
        firstName: "Sophia",
        lastName: "Anderson",
        username: "@SophiaA",
        email: "sophia.anderson@example.com",
        password: "qazwsx",
    },
];

export default users